# Generated by Django 4.0.2 on 2022-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
