# Generated by Django 4.0.2 on 2022-04-17 07:18

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_rate_created_alter_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logotype',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.upload_logotype),
        ),
    ]
