# Generated by Django 4.0.2 on 2022-03-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='currency_type',
        ),
    ]
