# Generated by Django 4.0.2 on 2022-03-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_rename_type_rate_currency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='currency_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='rate',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
