# Generated by Django 4.0.2 on 2022-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_contactmail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMail',
            new_name='ContactUsCreate',
        ),
    ]
